services:
  unicast-emitter:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - ./target/java-udp-programming-1.0-SNAPSHOT.jar
      - unicast-emitter
      - --host=unicast-receiver-1
      - --port=9876
      - --delay=0
      - --frequency=5000

  broadcast-emitter:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - broadcast-emitter
      - --host=255.255.255.255
      - --port=9876
      - --delay=5000
      - --frequency=30000

  multicast-emitter:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - multicast-emitter
      - --interface=eth0
      - --host=239.1.1.1
      - --port=9876
      - --delay=10000
      - --frequency=15000


  unicast-receiver-1:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - unicast-receiver
      - --port=9876

  unicast-receiver-2:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - unicast-receiver
      - --port=9876

  broadcast-receiver-1:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - broadcast-receiver
      - --port=9876

  broadcast-receiver-2:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - broadcast-receiver
      - --port=9876

  multicast-receiver-1:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - multicast-receiver
      - --interface=eth0
      - --host=239.1.1.1
      - --port=9876


  multicast-receiver-2:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - multicast-receiver
      - --interface=eth0
      - --host=239.1.1.1
      - --port=9876

  multicast-receiver-3:
    image: ghcr.io/molinaelgringo/java-udp-programming
    command:
      - java
      - -jar
      - java-udp-programming-1.0-SNAPSHOT.jar
      - multicast-receiver
      - --interface=eth0
      - --host=239.1.1.2
      - --port=9876